const ActionTypes = {
  FETCH_EVENTS_START: "FETCH_EVENTS_START",
  FETCH_EVENTS_SUCCESS: "FETCH_EVENTS_SUCCESS",
  FETCH_EVENTS_FAILURE: "FETCH_EVENTS_FAILURE",
  REGISTER_USER_START: "REGISTER_USER_START",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
  ADD_PERSONAL_INFO: "ADD_PERSONAL_INFO",
  ADD_INDIVIDUAL_EVENTS: "ADD_INDIVIDUAL_EVENTS",
  ADD_TEAM_EVENTS: "ADD_TEAM_EVENTS",
  ADD_AUTH_DATA: "ADD_AUTH_DATA",
  ADD_PAYMENT_DATA: "ADD_PAYMENT_DATA",
};

export default ActionTypes;
