const EventDetailsType = {
  GET_EVENT_DETAILS_START: "GET_EVENT_DETAILS_START",
  GET_EVENT_DETAILS_SUCCESS: "GET_EVENT_DETAILS_SUCCESS",
  GET_EVENT_DETAILS_FAILURE: "GET_EVENT_DETAILS_FAILURE",
  CLEAR_EVENT_DETAILS: "CLEAR_EVENT_DETAILS",
};

export default EventDetailsType;
