let timelineElements = [
  {
    id: 1,
    title: "Strigrays League - Gaming Jam",
    location: "Game Development, Offline",
    description: "",
    buttonText: "Read More",
    date: "March 24",
    icon: "event",
    link: "/strigrays-league",
  },
  {
    id: 2,
    title: "Battle Of The Ice - Gaming Tournament",
    location: "Online Gaming",
    description: "",
    buttonText: "Read More",
    date: "March 24",
    icon: "event",
  },
  {
    id: 3,
    title: "Zh3r0-Capture the Flag",
    location: "Capture the Flag",
    description: "",
    buttonText: "Read More",
    date: "March 24",
    icon: "event",
  },
  {
    id: 4,
    title: "Platonic",
    location: "Innovative idea proposal competition, Offline",
    description: "",
    buttonText: "Read More",
    date: "March 24",
    icon: "event",
  },
  {
    id: 5,
    title: "Bidders Coding Camp",
    location: "Coding event to earn points, offline",
    description: "",
    buttonText: "Read More",
    date: "March 24",
    icon: "workshop",
  },
  {
    id: 6,
    title: "BotBattleBash B3",
    location: "Building a ChatBot",
    description: "",
    buttonText: "Read More",
    date: "March 24",
    icon: "workshop",
  },
  {
    id: 7,
    title: "BotBattleBash B3",
    location: "Building a ChatBot",
    description: "",
    buttonText: "Read More",
    date: "March 24",
    icon: "workshop",
  },
];

export default timelineElements;
